### ISSUE TITLE
Question with respect to training the mediator

### ISSUE THREAD

**Issue by d12306** [XiaohangZhan/cdp#14]
Hi, @XiaohangZhan , thanks for your implementation.

You said in the paper, The mediator is trained on D_{l}, but actually you explained in the previous section that the input to the mediator is the relationships, the affinity and the local structures on the graphs derived from the unlabeled dataset. How do you get this on D_{l} for training the mediator, did you repeat the process again for the labeled data?

Thanks,

**Comment by XiaohangZhan** [comment]
Yes, in training the mediator, we need to extract those inputs of D_l as well.

**Comment by d12306** [comment]
Thanks for your clarification
