### ISSUE TITLE
Memory issue when computing affinity features

### ISSUE THREAD

**Issue by liuyvchi** [XiaohangZhan/cdp#16]
Hi, thanks for sharing your code

I am trying to reimplement CDP with my own data (the data size is similar to that in your paper). I got hundreds of millions of pairs after loading committee KNN, resulting in MemoryError when computing affinity features.  I can modify the source code of this part for lower memory requirements but that will increase the computation time significantly.

Could you please tell me your computation resource when you implement CDP? 

Many Thanks

Cheers

**Comment by XiaohangZhan** [comment]
Hi, the server I used has 256G memory. Indeed it costs a lot of memory, otherwise it will be very slow, you may have to increase your memory.
