### ISSUE TITLE
 Does it support data incremental processing?

### ISSUE THREAD

**Issue by aiot-tech** [XiaohangZhan/cdp#18]
Zhan,thank you for your outstanding work,and it help me a lot.By the way ,does it support data incremental processing?What if I want to process the data incrementally?

**Comment by XiaohangZhan** [comment]
Sorry, it does not support incremental or online clustering, you have to perform global clustering in each time.

**Comment by aiot-tech** [comment]
However,if I want to implement the function of incremental clustering, which modules of the code should I modify?

**Comment by XiaohangZhan** [comment]
It does not support incremental clustering in the algorithm aspect, hence you may not be able to achieve it via simply modifying some modules. If you find a way to extend CDP into incremental clustering, please tell me. I recommend you use some other algorithms specifically designed for incremental clustering.

**Comment by aiot-tech** [comment]
The performance of this algorithm is really awesome. If I use "vote" instead of "mediator" mode, is there any way to achieve incremental processing? If not, could you recommend some incremental clustering algorithms with similar performance to "cdp"?

**Comment by XiaohangZhan** [comment]
Here is a naive way to do so. Given an initial clustering results by CDP, you may assign a new sample to an existing cluster via linking it with its nearest neighbor, or obeying the majority of top-k neighbors. If the similarity between its nearest neighbor is below some threshold, then it forms a new cluster. I just came up with it casually, I cannot guarantee the performance of it.

**Comment by aiot-tech** [comment]
Thanks for your patient answer, I will have a try!~

**Comment by XiaohangZhan** [comment]
Good luck :)
