### ISSUE TITLE
Where is train_mediator located

### ISSUE THREAD

**Issue by fengjunlv** [XiaohangZhan/cdp#2]
Thanks for this great work. A quick question: train_mediator is called inside cdp but its implementation is not in the repo. Where can we find it?

**Comment by XiaohangZhan** [comment]
The code for mediator will be released soon. You can try "vote" at first, just refer to `experiments/example_vote/config.yaml`.

**Comment by fengjunlv** [comment]
got it. Thanks.  Looking forward to it...

**Comment by XiaohangZhan** [comment]
Hi, the full code and data are released now. I'm sorry for the delay.
