### ISSUE TITLE
about file list.txt

### ISSUE THREAD

**Issue by Linsongrong** [XiaohangZhan/cdp#20]
@XiaohangZhan Hello author. When I prepare my own data, the file list.txt is missing. Is this list file necessary? What is its role? Is the address index mentioning features? I already have the feature.bin file, do I not need list.txt, or assist in generating KNN graph? If there is no need to modify the code somewhere. Looking forward to your early reply.

**Comment by XiaohangZhan** [comment]
Not necessary. It was to check the length of the feature file previously.

**Comment by Linsongrong** [comment]
@XiaohangZhan Hello author, realize that you are one of the authors of the 20-year CVPR article Learning to Cluster Faces via Confidence and Connectivity Estimation, here I want to ask questions about the VEGCN project, it is about the test of gcn_v on large data sets, I am in When using GCN_V to test MS1M-part9, there was a problem of'out of memory'. If batch_size_per_gpu=1, the problem still exists. I would like to ask how to solve this problem. Looking forward to your reply。

**Comment by XiaohangZhan** [comment]
@Linsongrong You'd better directly contact Lei Yang for details: yl016@ie.cuhk.edu.hk, or raise the issue under: https://github.com/yl-1993/learn-to-cluster

**Comment by Linsongrong** [comment]
@XiaohangZhan Thank you for your reply, I will contact him back. When I reproduced your work, there were some problems. When I used the CDP single model to perform clustering experiments on MS1M part9, there was a problem when connecting to the cluster. ‘index 2645365 is out of bounds for axis 0 with size 578238
"What is the reason for this and how can I solve it?"
![image](https://user-images.githubusercontent.com/30062624/86451773-f8a64880-bd4d-11ea-8e99-d5fda2afdff7.png)
![image](https://user-images.githubusercontent.com/30062624/86451838-0c51af00-bd4e-11ea-99d9-f57c07e5fee0.png)

**Comment by XiaohangZhan** [comment]
Did you change the code? The original code won't raise errors like that. Here are tips for debugging:
1. Check if args.total_num is correct. if not, please ensure the list.txt file has correct number of lines and the feature file is correct. The content of list.txt does not matter, the number of lines should be correct.
2. Check if the maximal value in variable `pairs` in line 88 is less than args.total_num.
3. Check if the length of KNN results is equal to args.total_num.

**Comment by Linsongrong** [comment]
You are right, I solved the problem. Thanks
