### ISSUE TITLE
质疑

### ISSUE THREAD

**Issue by zhanghongruiupup** [XiaohangZhan/cdp#21]
emore_u200k实际为2577个类别，所以对于
method | #clusters | prec, recall, fscore | total time
* kmeans (ncluster=2577) | 2577 | 94.24, 74.89, 83.45 | 618.1s
我认为指标是可信的

但是对于其他的指标比如
method | #clusters | prec, recall, fscore | total time
HDBSCAN (min_samples=10) | 31354 | 99.35, 75.99, 86.11 | 4.87h
虽然看起来指标不错，但是HDBSCAN已经将emore_u200k分为31354个类别了，从正确的2577个类别到31354个类别，意味这存在将一个人脸类别分成了多个人脸类别，这是不太合理的吧

**Comment by zhanghongruiupup** [comment]
比如我用Knn,并设k=2，这样对于emore_u200k，能够得到10w的clusters，同时prec和recall都会接近100

**Comment by XiaohangZhan** [comment]
我不是很理解你的意思，HDBSCAN的number of clusters不是人为设定的，而是算法决定的，没法说合理不合理。。
10w的cluster，实际2577个类别，那么prec可以接近100，但recall会很低。如果用“质疑”这个标题，我还是希望能看到有真正的问题被指出，否则容易对其他人产生误导。谢谢。

**Comment by zhanghongruiupup** [comment]
感谢回复，接受用词问题。对于emore_u200k的指标，我关注的是聚类后得到的类别数，比如HDBSCAN虽然它的prec,recall不错，但最后聚类为31354个类别，远远超过实际的2577个类别，意味着存在同一个人的人脸分配多成多个类别的问题，个人理解

**Comment by XiaohangZhan** [comment]
聚类为31354个类别，远远超过实际的2577个类别，当然意味着同一个的不同脸被分到不同类别里。我们已经通过调节参数把HDBSCAN的fscore调到最高，然而还是出现了recall低的问题，这难道不是证明了HDBSCAN的缺陷，和CDP的优点吗？我不清楚你要质疑CDP的什么？

**Comment by zhanghongruiupup** [comment]
个人觉得评价指标不能真实反应聚类性能，比如HDBSCAN，将实际2577个类别聚类成31354个类别，效果很差。但是单纯用prec,recall，两个指标分别为99.35和75.99，看起来又不错

**Comment by XiaohangZhan** [comment]
> 个人觉得评价指标不能真实反应聚类性能，比如HDBSCAN，将实际2577个类别聚类成31354个类别，效果很差。但是单纯用prec,recall，两个指标分别为99.35和75.99，看起来又不错

1. 75.99并不高，CDP有90+。正是因为聚类数量太多，所以才导致只有75.99的recall。ApproxRankOrder聚出来更多的85150类，recall降到了16.93。
2. prec和recall是衡量聚类效果的一个通用标准，而聚类数量并不是。反应聚类性能并不是靠直观感觉。
3. 我建议你跑一下HDBSCAN的代码（可以用这个repo里的run_baselines.sh来跑），把超参数调一调，让聚类数量降下来，甚至接近真实的情况，你再看看prec, recall分别是多少，你就明白了。
