### ISSUE TITLE
 the question about nmslib 

### ISSUE THREAD

**Issue by wangyujie413** [XiaohangZhan/cdp#6]
when i use the command  `pip install nmslib` on windows,
error:
`Building wheels for collected packages: nmslib
  Running setup.py bdist_wheel for nmslib ... error
  Complete output from command C:\Users\Administrator\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-va5h3yd3\\nmslib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-vu3x5ox6 --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'nmslib' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools`

Do i have to install  "Microsoft Visual C++'' ?

**Comment by XiaohangZhan** [comment]
Windows is not recommended for this code base. Please use Linux.
