### ISSUE TITLE
some question about the code

### ISSUE THREAD

**Issue by wangyujie413** [XiaohangZhan/cdp#7]
感谢你的分享！在看代码时我有一些疑惑：
1.unabled data 里的list.txt和meta.txt内容分别是无标签数据的标签么？这个怎么来的，既然是无标签数据怎么会有标签名称的？
2.在cdp.py中
`def sample():
    vote_num += (tile_knn == tile_cmt).sum(axis=2)
selidx = np.where((simi > th) & (vote_num >= accept) & (knn != -1) & (knn != anchor))`
中，vote_num和accept参数指的是什么？  (knn != anchor)指的是不满足什么条件的样本？
希望得到您的解答，谢谢！

**Comment by XiaohangZhan** [comment]
1. unlabeled_data里的meta.txt是用来evaluate算法性能的，算法只会在evaluate阶段用上它。如果单纯聚类而不evaluate的话，不需要meta.txt，并且config.yaml里evaluation需要设为False.
2. vote_num: Nxk array, vote_num[i, j]表示认为第i个sample (anchor)与i的第j个neighbor是同类的committee members的数量。accept是一个阈值，如果vote_num[i, j]超过这个阈值，则(i, knn[i, j])被选中成为一个pair。(knn != anchor)，因为nmslib计算的原因，会存在knn[i,j] = i的情况，自己与自己构成的pair是无效的，因此去除。

**Comment by wangyujie413** [comment]
谢谢回复。
那list.txt文件里的内容作用呢？
我看这个文件里的命名规则是
`0/0_1.jpg
0/0_2.jpg
5/5_303.jpg
5/5_304.jpg`
这个不是代表已经把unlabled data的标签为0或5了？
主要想了解你是怎么为unlabled data命名的？

**Comment by XiaohangZhan** [comment]
数据集下载下来就是这样子命名的。算法里当然没有用list里的文件名来判断类别。。。

**Comment by wangyujie413** [comment]
不好意思，现在发现了。。
请问发布的代码里是不是没有affinity.npy，relationship.npy，structure.npy，pair_label.npy，pairs.npy文件生成的部分？

**Comment by XiaohangZhan** [comment]
有。create _pair_set.py。跑的时候会自动执行生成这些文件。

**Comment by wangyujie413** [comment]
非常感谢，我把程序跑起来了，的确有。
