### ISSUE TITLE
how to calculate the evaluation indicator

### ISSUE THREAD

**Issue by panyiming** [XiaohangZhan/cdp#8]
```python
(singular removed) prec / recall / fscore: 97.2, 97.33, 97.26
(singular kept) prec / recall / fscore: 97.2, 94.93, 96.05
```
This is the output when i run this code on my own data, what is the exact definition of precision and recall?  And i can not fully understand the code in  eval_cluster.py.

**Comment by XiaohangZhan** [comment]
precision: TP / (TP + FN), recall: TP / (TP + FP).
TP, FP, FN are computed in pair-wise manner, please refer to [FMI Score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.fowlkes_mallows_score.html#sklearn.metrics.fowlkes_mallows_score).
Here in my code I replaced FMI with Fscore, which is a little bit different with FMI score. Fscore = 2 * prec * recall / (prec + recall), while FMI = sqrt(prec * recall)

**Comment by panyiming** [comment]
Thanks for your reply.It seems that  precision and recall were misplaced. But actually  i used the same definition as you referred but can not get the same output of precision as the code gives.
The example is as follows:
```python
pred_label = [0,0,1,1,2,2,3,4,5,5,6]
true_label =  [0,0,1,1,2,3,4,5,5,5,5]
```
I am not clear about the exact process of computing precision and recall because there are some difference compared to common recall and precision. Would you like to use this example to explain your process.Thank you in advance.

**Comment by XiaohangZhan** [comment]
The precision and recall are not misplaced. For this toy example:
TP: indices of true positive pairs in pred_label: (0,1), (2,3), (8,9)
FN: indices of false negative pairs in pred_label: (4,5)
FP: indices of false negative pairs in pred_label: (7,8), (7,9), (7,10), (8,10), (9,10)
hence precision = TP / (TP + FN) = 3 / (3 + 1) = 0.75
recall = TP / (TP + FP) = 3 / (3 + 5) = 0.375

I guess you misunderstood FP and FN. Here is the definition from [sklearn FMI Score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.fowlkes_mallows_score.html#sklearn.metrics.fowlkes_mallows_score)
False Positive: the number of pair of points that belongs in the same clusters in labels_true and not in labels_pred
False Negative: the number of pair of points that belongs in the same clusters in labels_pred and not in labels_True

**Comment by panyiming** [comment]
Thank you so much. I figured it out.@XiaohangZhan
